### ISSUE TITLE
Method 'complete' raises error due to unbound variables

### ISSUE THREAD

**Issue by HereAround** [kamalsaleh/CddInterface#7]
When I load CddInterface, I obtain a message regarding "unbound global variables":

Syntax warning: Unbound global variable in /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CddInterface/gap/polyhedra.gi:513
     L := CddInterface_FacesWithDimensionAndInteriorPoints( M, d );
                                                          ^
Syntax warning: Unbound global variable in /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CddInterface/gap/polyhedra.gi:538
     L := CddInterface_FacesWithDimensionAndInteriorPoints( M, 0 );
                                                          ^
Syntax warning: Unbound global variable in /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CddInterface/gap/polyhedra.gi:622
     L := CddInterface_FacesWithDimensionAndInteriorPoints( M, 0 );
                                                          ^
Syntax warning: Unbound global variable in /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/CddInterface/gap/polyhedra.gi:643
     L := CddInterface_FacesWithDimensionAndInteriorPoints( M, 0 );
                                                          ^
This seems to raise an error, whenever I check if a fan is complete. Here is an example with the fan of P2:

LoadPackage( "NConvex" );
rays := [ [1,0],[0,1],[-1,-1] ];
cones := [ [1,2],[1,3],[2,3] ];
fan := Fan( rays, cones );
IsComplete( fan );

This raises the following error:

Error, Variable: 'CddInterface_FacesWithDimensionAndInteriorPoints' must have an assi\
gned value in
  L := CddInterface_FacesWithDimensionAndInteriorPoints( M, d )

I use the following versions:
CddInterface: 2e70e3127cd3800059f370fb33a498c991ce0e62
NConvex: bef7783a8c57b59bffea26265c2c95dcd37db6ab
gap: GAP 4.10.0 of 01-Nov-2018

**Comment by kamalsaleh** [comment]
These errors can happen only if the package is not properly compiled. Since all of the global functions are in the C part of the package. Please try to compile it and tell me if the problem remains.

**Comment by HereAround** [comment]
You are right. After recompiling, the problem disappeared. Thanks!
