### ISSUE TITLE
Clarify what the canonical repository for this package is / fix IssueTrackerURL

### ISSUE THREAD

**Issue by fingolfin** [kamalsaleh/CddInterface#9]
The `PackageInfo.g` for this package gives `https://github.com/homalg-project/CddInterface/issues` as the `IssueTrackerURL` -- but that does not work. On the other hand, this repository here has `https://github.com/kamalsaleh/CddInterface/issues`

This should be resolved one way or the another -- either by enabling issues on the one project, or fixing the `IssueTrackerURL` (probably by fixing `SourceRepository.URL` -- but of course that then would also affect several other derived URLs).

**Comment by kamalsaleh** [comment]
The issues are now enabled in homalg https://github.com/homalg-project/CddInterface/issues

**Comment by fingolfin** [comment]
Huh? I am really curious what those technical reasons are. But anyway, good to know it is being resolved.

**Comment by kamalsaleh** [comment]
I need to figure it out. I am following the steps in the github pages for gap and at the end I expect to find a website of the package under https://homalg-project.github.io/CddInterface ; But instead, an error 404 is returned. The gh-pages branch in  `homalg-project/CddInterface` is still available. But as already said, i seems to have no effect.

**Comment by fingolfin** [comment]
Have you already checked the GitHub Pages settings under https://github.com/homalg-project/CddInterface/settings ?

**Comment by kamalsaleh** [comment]
Not yet. I don't have access to the settings of this package in homalg-project. But this should be clarified by end of the day after discussing it with Mohamed.

**Comment by fingolfin** [comment]
Thanks for the fix. Note that the same issue also affects NConvec

**Comment by kamalsaleh** [comment]
Thanks for the issue.
NConvex issues are due tomorrow :)
